# coding: utf-8

"""
    Groovy API

    AudioShake API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2_xx1 import InlineResponse2XX1  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2XX1(unittest.TestCase):
    """InlineResponse2XX1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2XX1(self):
        """Test InlineResponse2XX1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2_xx1.InlineResponse2XX1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
