# coding: utf-8

"""
    Groovy API

    AudioShake API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.upload_api import UploadApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUploadApi(unittest.TestCase):
    """UploadApi unit test stubs"""

    def setUp(self):
        self.api = UploadApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_upload_audio_link_post(self):
        """Test case for upload_audio_link_post

        Create a new asset from a file link.  # noqa: E501
        """
        pass

    def test_upload_link_post(self):
        """Test case for upload_link_post

        Create a new asset from a file link.  # noqa: E501
        """
        pass

    def test_upload_post(self):
        """Test case for upload_post

        Create a new asset.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
