# coding: utf-8

"""
    Groovy API

    AudioShake API  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import audioshake
from audioshake.models.inline_response2_xx_job_status_info import InlineResponse2XXJobStatusInfo  # noqa: E501
from audioshake.rest import ApiException


class TestInlineResponse2XXJobStatusInfo(unittest.TestCase):
    """InlineResponse2XXJobStatusInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2XXJobStatusInfo(self):
        """Test InlineResponse2XXJobStatusInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = audioshake.models.inline_response2_xx_job_status_info.InlineResponse2XXJobStatusInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
