# coding: utf-8

"""
    Groovy API

    AudioShake API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2_xx_job import InlineResponse2XXJob  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2XXJob(unittest.TestCase):
    """InlineResponse2XXJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2XXJob(self):
        """Test InlineResponse2XXJob"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2_xx_job.InlineResponse2XXJob()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
