# coding: utf-8

"""
    Groovy API

    AudioShake API  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import audioshake
from audioshake.models.inline_response2_xx_job_stem_metadata import InlineResponse2XXJobStemMetadata  # noqa: E501
from audioshake.rest import ApiException


class TestInlineResponse2XXJobStemMetadata(unittest.TestCase):
    """InlineResponse2XXJobStemMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2XXJobStemMetadata(self):
        """Test InlineResponse2XXJobStemMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = audioshake.models.inline_response2_xx_job_stem_metadata.InlineResponse2XXJobStemMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
