# coding: utf-8

"""
    Groovy API

    AudioShake API  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import audioshake
from audioshake.api.job_api import JobApi  # noqa: E501
from audioshake.rest import ApiException


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self):
        self.api = JobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_job_id_get(self):
        """Test case for job_id_get

        Get a job given an Id.  # noqa: E501
        """
        pass

    def test_job_post(self):
        """Test case for job_post

        Create a new job.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
