# coding: utf-8

"""
    Groovy API

    AudioShake API  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import audioshake
from audioshake.models.upload_body import UploadBody  # noqa: E501
from audioshake.rest import ApiException


class TestUploadBody(unittest.TestCase):
    """UploadBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUploadBody(self):
        """Test UploadBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = audioshake.models.upload_body.UploadBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
