# coding: utf-8

# flake8: noqa

"""
    Groovy API

    AudioShake API  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.job_api import JobApi
from swagger_client.api.upload_api import UploadApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.Asset import Asset
from swagger_client.models.Job import Job
from swagger_client.models.inline_response2_xx import InlineResponse2XX
from swagger_client.models.inline_response2_xx1 import InlineResponse2XX1
from swagger_client.models.inline_response2_xx_job import InlineResponse2XXJob
from swagger_client.models.inline_response2_xx_job_source_asset import InlineResponse2XXJobSourceAsset
from swagger_client.models.inline_response2_xx_job_source_asset_jobs import InlineResponse2XXJobSourceAssetJobs
from swagger_client.models.inline_response2_xx_job_source_asset_stem_assets import InlineResponse2XXJobSourceAssetStemAssets
from swagger_client.models.inline_response2_xx_job_status_info import InlineResponse2XXJobStatusInfo
from swagger_client.models.inline_response2_xx_job_stem_assets import InlineResponse2XXJobStemAssets
from swagger_client.models.inline_response2_xx_job_stem_metadata import InlineResponse2XXJobStemMetadata
from swagger_client.models.job_body import JobBody
from swagger_client.models.job_other_source_assets import JobOtherSourceAssets
from swagger_client.models.job_stem_metadata import JobStemMetadata
from swagger_client.models.upload_audiolink_body import UploadAudiolinkBody
from swagger_client.models.upload_body import UploadBody
from swagger_client.models.upload_link_body import UploadLinkBody
