# coding: utf-8

"""
    Groovy API

    AudioShake API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2XXJobSourceAssetJobs(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stem_assets': 'list[InlineResponse2XXJobSourceAssetStemAssets]'
    }

    attribute_map = {
        'stem_assets': 'stemAssets'
    }

    def __init__(self, stem_assets=None):  # noqa: E501
        """InlineResponse2XXJobSourceAssetJobs - a model defined in Swagger"""  # noqa: E501
        self._stem_assets = None
        self.discriminator = None
        if stem_assets is not None:
            self.stem_assets = stem_assets

    @property
    def stem_assets(self):
        """Gets the stem_assets of this InlineResponse2XXJobSourceAssetJobs.  # noqa: E501

        Array of stem assets generated for the job  # noqa: E501

        :return: The stem_assets of this InlineResponse2XXJobSourceAssetJobs.  # noqa: E501
        :rtype: list[InlineResponse2XXJobSourceAssetStemAssets]
        """
        return self._stem_assets

    @stem_assets.setter
    def stem_assets(self, stem_assets):
        """Sets the stem_assets of this InlineResponse2XXJobSourceAssetJobs.

        Array of stem assets generated for the job  # noqa: E501

        :param stem_assets: The stem_assets of this InlineResponse2XXJobSourceAssetJobs.  # noqa: E501
        :type: list[InlineResponse2XXJobSourceAssetStemAssets]
        """

        self._stem_assets = stem_assets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2XXJobSourceAssetJobs, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2XXJobSourceAssetJobs):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
