# coding: utf-8

"""
    Groovy API

    AudioShake API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobStemMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'format': 'str',
        'stem_name': 'str',
        'max_track_length': 'float',
        'watermark_interval': 'float',
        'custom_property': 'str',
        'residual': 'bool',
        'preview': 'bool',
        'user_session_id': 'str',
        'audio_id': 'str',
        'license_id': 'str',
        'priority': 'float',
        'failure_test': 'float',
        'is_test_job': 'bool'
    }

    attribute_map = {
        'format': 'format',
        'stem_name': 'stemName',
        'max_track_length': 'maxTrackLength',
        'watermark_interval': 'watermarkInterval',
        'custom_property': 'customProperty',
        'residual': 'residual',
        'preview': 'preview',
        'user_session_id': 'userSessionId',
        'audio_id': 'audioId',
        'license_id': 'licenseId',
        'priority': 'priority',
        'failure_test': 'failureTest',
        'is_test_job': 'isTestJob'
    }

    def __init__(self, format=None, stem_name=None, max_track_length=None, watermark_interval=None, custom_property=None, residual=None, preview=None, user_session_id=None, audio_id=None, license_id=None, priority=None, failure_test=None, is_test_job=None):  # noqa: E501
        """JobStemMetadata - a model defined in Swagger"""  # noqa: E501
        self._format = None
        self._stem_name = None
        self._max_track_length = None
        self._watermark_interval = None
        self._custom_property = None
        self._residual = None
        self._preview = None
        self._user_session_id = None
        self._audio_id = None
        self._license_id = None
        self._priority = None
        self._failure_test = None
        self._is_test_job = None
        self.discriminator = None
        self.format = format
        self.stem_name = stem_name
        if max_track_length is not None:
            self.max_track_length = max_track_length
        if watermark_interval is not None:
            self.watermark_interval = watermark_interval
        if custom_property is not None:
            self.custom_property = custom_property
        if residual is not None:
            self.residual = residual
        if preview is not None:
            self.preview = preview
        if user_session_id is not None:
            self.user_session_id = user_session_id
        if audio_id is not None:
            self.audio_id = audio_id
        if license_id is not None:
            self.license_id = license_id
        if priority is not None:
            self.priority = priority
        if failure_test is not None:
            self.failure_test = failure_test
        if is_test_job is not None:
            self.is_test_job = is_test_job

    @property
    def format(self):
        """Gets the format of this JobStemMetadata.  # noqa: E501


        :return: The format of this JobStemMetadata.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this JobStemMetadata.


        :param format: The format of this JobStemMetadata.  # noqa: E501
        :type: str
        """
        if format is None:
            raise ValueError("Invalid value for `format`, must not be `None`")  # noqa: E501
        allowed_values = ["wav", "flac", "mp3", "aiff"]  # noqa: E501
        if format not in allowed_values:
            raise ValueError(
                "Invalid value for `format` ({0}), must be one of {1}"  # noqa: E501
                .format(format, allowed_values)
            )

        self._format = format

    @property
    def stem_name(self):
        """Gets the stem_name of this JobStemMetadata.  # noqa: E501

        The stem you want to generate.  # noqa: E501

        :return: The stem_name of this JobStemMetadata.  # noqa: E501
        :rtype: str
        """
        return self._stem_name

    @stem_name.setter
    def stem_name(self, stem_name):
        """Sets the stem_name of this JobStemMetadata.

        The stem you want to generate.  # noqa: E501

        :param stem_name: The stem_name of this JobStemMetadata.  # noqa: E501
        :type: str
        """
        if stem_name is None:
            raise ValueError("Invalid value for `stem_name`, must not be `None`")  # noqa: E501
        allowed_values = ["dialogue_48", "transcription", "alignment", "transcription_2", "alignment_2", "instrumental", "vocals", "drums", "bass", "other", "guitar", "other-x-guitar", "piano", "wind", "speech", "music", "dialogue", "dialogue_16"]  # noqa: E501
        if stem_name not in allowed_values:
            raise ValueError(
                "Invalid value for `stem_name` ({0}), must be one of {1}"  # noqa: E501
                .format(stem_name, allowed_values)
            )

        self._stem_name = stem_name

    @property
    def max_track_length(self):
        """Gets the max_track_length of this JobStemMetadata.  # noqa: E501

        Track length in seconds. optional property  # noqa: E501

        :return: The max_track_length of this JobStemMetadata.  # noqa: E501
        :rtype: float
        """
        return self._max_track_length

    @max_track_length.setter
    def max_track_length(self, max_track_length):
        """Sets the max_track_length of this JobStemMetadata.

        Track length in seconds. optional property  # noqa: E501

        :param max_track_length: The max_track_length of this JobStemMetadata.  # noqa: E501
        :type: float
        """

        self._max_track_length = max_track_length

    @property
    def watermark_interval(self):
        """Gets the watermark_interval of this JobStemMetadata.  # noqa: E501

        Interval for watermark in seconds. optional property  # noqa: E501

        :return: The watermark_interval of this JobStemMetadata.  # noqa: E501
        :rtype: float
        """
        return self._watermark_interval

    @watermark_interval.setter
    def watermark_interval(self, watermark_interval):
        """Sets the watermark_interval of this JobStemMetadata.

        Interval for watermark in seconds. optional property  # noqa: E501

        :param watermark_interval: The watermark_interval of this JobStemMetadata.  # noqa: E501
        :type: float
        """

        self._watermark_interval = watermark_interval

    @property
    def custom_property(self):
        """Gets the custom_property of this JobStemMetadata.  # noqa: E501

        Pass any custom string for clients use or debugging. max 1000 chars. optional property  # noqa: E501

        :return: The custom_property of this JobStemMetadata.  # noqa: E501
        :rtype: str
        """
        return self._custom_property

    @custom_property.setter
    def custom_property(self, custom_property):
        """Sets the custom_property of this JobStemMetadata.

        Pass any custom string for clients use or debugging. max 1000 chars. optional property  # noqa: E501

        :param custom_property: The custom_property of this JobStemMetadata.  # noqa: E501
        :type: str
        """

        self._custom_property = custom_property

    @property
    def residual(self):
        """Gets the residual of this JobStemMetadata.  # noqa: E501

        Sets flag to return back separate residual file. optional property  # noqa: E501

        :return: The residual of this JobStemMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._residual

    @residual.setter
    def residual(self, residual):
        """Sets the residual of this JobStemMetadata.

        Sets flag to return back separate residual file. optional property  # noqa: E501

        :param residual: The residual of this JobStemMetadata.  # noqa: E501
        :type: bool
        """

        self._residual = residual

    @property
    def preview(self):
        """Gets the preview of this JobStemMetadata.  # noqa: E501

        Sets flag to return back separate preview mp3 file. optional property  # noqa: E501

        :return: The preview of this JobStemMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._preview

    @preview.setter
    def preview(self, preview):
        """Sets the preview of this JobStemMetadata.

        Sets flag to return back separate preview mp3 file. optional property  # noqa: E501

        :param preview: The preview of this JobStemMetadata.  # noqa: E501
        :type: bool
        """

        self._preview = preview

    @property
    def user_session_id(self):
        """Gets the user_session_id of this JobStemMetadata.  # noqa: E501

        Represents the userSessionId associated with this job  # noqa: E501

        :return: The user_session_id of this JobStemMetadata.  # noqa: E501
        :rtype: str
        """
        return self._user_session_id

    @user_session_id.setter
    def user_session_id(self, user_session_id):
        """Sets the user_session_id of this JobStemMetadata.

        Represents the userSessionId associated with this job  # noqa: E501

        :param user_session_id: The user_session_id of this JobStemMetadata.  # noqa: E501
        :type: str
        """

        self._user_session_id = user_session_id

    @property
    def audio_id(self):
        """Gets the audio_id of this JobStemMetadata.  # noqa: E501

        Represents the custom unique audio file id associated with this job  # noqa: E501

        :return: The audio_id of this JobStemMetadata.  # noqa: E501
        :rtype: str
        """
        return self._audio_id

    @audio_id.setter
    def audio_id(self, audio_id):
        """Sets the audio_id of this JobStemMetadata.

        Represents the custom unique audio file id associated with this job  # noqa: E501

        :param audio_id: The audio_id of this JobStemMetadata.  # noqa: E501
        :type: str
        """

        self._audio_id = audio_id

    @property
    def license_id(self):
        """Gets the license_id of this JobStemMetadata.  # noqa: E501


        :return: The license_id of this JobStemMetadata.  # noqa: E501
        :rtype: str
        """
        return self._license_id

    @license_id.setter
    def license_id(self, license_id):
        """Sets the license_id of this JobStemMetadata.


        :param license_id: The license_id of this JobStemMetadata.  # noqa: E501
        :type: str
        """

        self._license_id = license_id

    @property
    def priority(self):
        """Gets the priority of this JobStemMetadata.  # noqa: E501


        :return: The priority of this JobStemMetadata.  # noqa: E501
        :rtype: float
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this JobStemMetadata.


        :param priority: The priority of this JobStemMetadata.  # noqa: E501
        :type: float
        """

        self._priority = priority

    @property
    def failure_test(self):
        """Gets the failure_test of this JobStemMetadata.  # noqa: E501

        If this param has a value, use the corresponding code to force a failed test  # noqa: E501

        :return: The failure_test of this JobStemMetadata.  # noqa: E501
        :rtype: float
        """
        return self._failure_test

    @failure_test.setter
    def failure_test(self, failure_test):
        """Sets the failure_test of this JobStemMetadata.

        If this param has a value, use the corresponding code to force a failed test  # noqa: E501

        :param failure_test: The failure_test of this JobStemMetadata.  # noqa: E501
        :type: float
        """

        self._failure_test = failure_test

    @property
    def is_test_job(self):
        """Gets the is_test_job of this JobStemMetadata.  # noqa: E501

        Determines whether a job is a \"test job\" or not  # noqa: E501

        :return: The is_test_job of this JobStemMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._is_test_job

    @is_test_job.setter
    def is_test_job(self, is_test_job):
        """Sets the is_test_job of this JobStemMetadata.

        Determines whether a job is a \"test job\" or not  # noqa: E501

        :param is_test_job: The is_test_job of this JobStemMetadata.  # noqa: E501
        :type: bool
        """

        self._is_test_job = is_test_job

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobStemMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobStemMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
